<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.IO.Ports" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tokens\Tokens.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Pm3UsbApi.Tests" />
        <InternalsVisibleTo Include="NativeT55Probe" />
    </ItemGroup>

</Project>
